###compare_TnP_data_mc(TString coll="pp", TString cap="_Ze10e10", TString ver="v9", bool doWeight=true)
root -l -b -q 'compare_TnP_data_mc.C++("pp","_Ze10e10","v9",1)'
root -l -b -q 'compare_TnP_data_mc.C++("pp","_Ze10e10","v9",0)'
root -l -b -q 'compare_TnP_data_mc.C++("pp","_Ze10e10_Ze30eeJet","v9",1)'
root -l -b -q 'compare_TnP_data_mc.C++("pp","_Ze10e10_Ze30eeJet","v9",0)'
root -l -b -q 'compare_TnP_data_mc.C++("pp","_Ze30eeJet","v9",1)'
root -l -b -q 'compare_TnP_data_mc.C++("pp","_Ze30eeJet","v9",0)'
root -l -b -q 'compare_TnP_data_mc.C++("pp","_Ze10e10","v10",1)'
root -l -b -q 'compare_TnP_data_mc.C++("pp","_Ze10e10","v10",0)'
root -l -b -q 'compare_TnP_data_mc.C++("pp","_Ze10e10_Ze30eeJet","v10",1)'
root -l -b -q 'compare_TnP_data_mc.C++("pp","_Ze10e10_Ze30eeJet","v10",0)'
root -l -b -q 'compare_TnP_data_mc.C++("pp","_Ze30eeJet","v10",1)'
root -l -b -q 'compare_TnP_data_mc.C++("pp","_Ze30eeJet","v10",0)'
root -l -b -q 'compare_TnP_data_mc.C++("pp","_Ze10e10","v11",1)'
root -l -b -q 'compare_TnP_data_mc.C++("pp","_Ze10e10","v11",0)'
root -l -b -q 'compare_TnP_data_mc.C++("pp","_Ze10e10","v12",1)'
root -l -b -q 'compare_TnP_data_mc.C++("pp","_Ze10e10","v12",0)'
